export default {
  es: {
    "Amazon Soy Ports": 'Puertos de soja en la Amazonía',
    "Investors are sinking hundreds of millions of dollars into private port facilities along the Amazon river and its tributaries to move agricultural commodities downriver from Brazil’s interior to the Atlantic coast and on to overseas markets":'Se invierten cientos de millones de dólares en instalaciones portuarias privadas a lo largo del río Amazonas y sus afluentes para trasladar productos agrícolas desde el interior de Brasil río abajo hasta la Costa Atlántica y hacia los mercados extranjeros',
    "Published": 'Publicado',
    "scroll down to discover": 'haz scroll para continuar',
    "Cartography by Willie Shubert for Mongabay.": 'Cartografía por Willie Shubert para Mongabay',
    "Turning the Amazon river into an industrial waterway": 'Convirtiendo el rio amazonas en una vía navegable industrial',
    "Brazil’s government has had major plans to exploit large portions of its 35,000-kilometers (22,000-miles) of waterways since the 1970s. Yet, it was mostly privately funded projects that went ahead. Today, the nation’s navigable waterways represent a third of its potential.":'Desde la década de 1970, el gobierno de Brasil ha tenido grandes planes para explotar extensas porciones de sus 35 000 kilómetros de vías fluviales. Sin embargo, fueron principalmente proyectos financiados con fondos privados los que siguieron adelante. Hoy en día, las vías navegables de la nación representan un tercio de su potencial',
    "Following the road north":'El camino de la carretera hacia el norte',
    "The northward expansion of Amazon roadbuilding over recent decades opened truck/barge transit corridors to the Amazon River and Atlantic Ocean that run adjacent to Indigenous territories and cause deforestation. However, these northern routes, do let agribusiness bypass a long, rugged road journey, and the queues of trucks clogging Brazil’s southern ports at Paranaguá and Santos.":'Durante las últimas décadas la expansión hacia el norte de la construcción de carreteras en la Amazonía abrió corredores de tránsito de camiones/embarcaciones hacia el río Amazonas y el océano Atlántico que corren adyacentes a territorios indígenas y causan deforestación. Sin embargo, estas rutas del norte permiten que la agroindustria evite un largo y accidentado viaje por carretera y las colas de camiones que obstruyen los puertos del sur de Brasil en Paranaguá y Santos.',
    "An agricultural heartland to the south":'Creación de un centro agrícola al sureste',
    "In July 2006, major commodities companies working in Brazil voluntarily agreed to cease purchases of soy produced in any Amazon area deforested after that year. The Amazon Soy Moratorium was hugely successful, but critics say saving the rainforest was only possible because soy production shifted to the vast Cerrado savanna, which lies to the south and east of the Amazon basin.":'En julio de 2006, grandes empresas de productos básicos que operan en Brasil acordaron voluntariamente cesar la compra de soya producida en áreas deforestadas de la Amazonía después de ese año. La Moratoria de la Soya en la Amazonía fue un gran éxito, pero los críticos dicen que la única razón por la que se pudo salvar a la selva tropical fue porque la producción de soya se trasladó a la vasta sabana del Cerrado, que se encuentra al sur y al este de la cuenca del Amazonas.',
    "A forgotten biodiversity hotspot":'Deforestación de un hotspot de biodiversidad',
    "Half of the Cerrado biome, one of the earth’s top biodiversity hotspots, has already been lost to cattle ranches and soy, corn and cotton plantations. Today, the savanna is losing its native vegetation faster than any part of Brazil, including the Amazon.":'La mitad del bioma del Cerrado, uno de los hotspots de biodiversidad más importantes del planeta, ya se ha perdido debido a la ganadería y las plantaciones de soya, maíz y algodón. Hoy, la sabana está perdiendo su vegetación nativa más rápido que cualquier parte de Brasil, incluida la Amazonía.',
    "Porto Velho":'Porto Velho',
    "Soy-loaded trucks travel from Mato Grosso state 1,000 kilometers (600 miles) along the BR-364 highway to the city of Porto Velho public port in Rondônia state. There, Hermasa, a subsidiary of agribusiness Amaggi, built silos in a leased portion of the public port, and moved soy from trucks to Madeira River barges. More recently, Hermasa built its own private port in the city. From Porto Velho, barges sail 1,000 kilometers downstream to a private Amaggi port at the city of Itacoatiara. From there, big ships travel downriver to the Atlantic coast and on to overseas markets.":'Los camiones cargados de soya viajan 1000 kilómetros desde el estado de Mato Grosso a lo largo de la carretera BR-364 hasta el puerto público de la ciudad de Porto Velho en el estado de Rondônia. Allí, Hermasa, una subsidiaria de la agroempresa Amaggi, construyó graneros en una área arrendada del puerto público y trasladó soya de camiones a embarcaciones en el río Madeira. Más recientemente, Hermasa construyó su propio puerto privado en la ciudad. Desde Porto Velho, las embarcaciones navegan 1000 kilómetros río abajo hasta un puerto privado de Amaggi en la ciudad de Itacoatiara. Desde allí, grandes embarcaciones viajan río abajo hasta la Costa Atlántica y luego hacia los mercados internacionales',
    "Itaituba":'Itaituba',
    "Since the passage of a 2013 law that enabled the creation of private river ports, at least ten industrial complexes have been built around the city of Itaituba in Pará state, in a transportation hub linking the BR-163 highway with the Tapajós River. Most are connected to agribusiness commodities giants. Cargill, Hidrovias do Brasil, Cianport and Unitapajós (a joint-venture between Bunge and Amaggi) own and operate the main ports. Together, the companies have invested over US$150 million in these private facilities.":'Desde la aprobación de una ley de 2013 que permitió la creación de puertos fluviales privados, se han construido al menos diez complejos industriales alrededor de la ciudad de Itaituba en el estado de Pará, en un centro de transporte que une la carretera BR-163 con el río Tapajós. La mayoría está relacionada con los gigantes de la agroindustria. Cargill, Hidrovias do Brasil, Cianport y Unitapajós (una empresa conjunta entre Bunge y Amaggi) poseen y operan los principales puertos. Juntas, las empresas han invertido más de USD 150 millones en estas instalaciones privadas.',
    "Santarém":'Santarém',
    "Five mostly agribusiness companies are eyeing the Maicá Lake, near the port complex of Santarém, Pará state,  as the next target for port development in the region. Some port projects have stalled after intense resistance by activists over the last seven years, but one has been built; a fuel port. However, the company responsible, Atem’s, lacked the required permits and in March, prosecutors filed criminal charges against the firm.":'Cinco empresas, en su mayoría agroindustriales, están considerando el lago Maicá, cerca del complejo portuario de Santarém, estado de Pará, como el próximo objetivo para el desarrollo portuario en la región. Algunos proyectos portuarios se han estancado tras una intensa resistencia de los activistas durante los últimos siete años, pero se ha construido uno; un puerto de combustible. Sin embargo, debido a que la empresa responsable, Atem’s, carecía de los permisos requeridos, en marzo, los fiscales presentaron cargos penales contra la empresa',
    "Barcarena":'Barcarena',
    "Pará state’s Barcarena complex began with the public Vila do Conde port, established in 1985. It was built to respond to demand from the region’s mining companies, including Vale, Brazil’s largest mining firm. In the 2000’s, Barcarena’s river port complex began to receive increased demand from agribusiness, as it sought a route through the Amazon.":'El complejo Barcarena del estado de Pará comenzó con el puerto público de Vila do Conde, establecido en 1985. Fue construido para responder a la demanda de las empresas mineras de la región, incluida Vale, la empresa minera más grande de Brasil. En la década de 2000, el complejo portuario fluvial de Barcarena comenzó a recibir una mayor demanda de la agroindustria, ya que buscaba una ruta a través de la Amazonía.'
  }
};
